services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - botnet
    volumes:
      - .:/usr/src/app

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - app
      - redis
    networks:
      - botnet

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
