version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - botnet
    volumes:
      - .:/usr/src/app

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - app
    networks:
      - botnet

networks:
  botnet:
    driver: bridge